### PR TITLE
Add timeout to all ConnectLE() and Scan() methods

### PR DESCRIPTION
**Pull request by zxzxwu**
Current `ConnectLE()` and `Scan()` methods miss a native timeout condition, so timeout must be set explicitly to avoid halting the tests.

### CODE REVIEW

**Comment by uael** [comment]
We need something that works for non-`async` tests as well, using a thread or a signal ? :thinking:

**Comment by uael** [comment]
Or we can add something like this in the `setup_test` ?
```python
import signal

def setup_test(self) -> None:
    signal.signal(signal.SIGALRM, lambda _signum, _frame: raise TimeoutError("test timed out"))
    signal.alarm(30)
```

**Comment by DeltaEvo** [comment]
Could we instead set a default deadline on GRPC calls ?

**Comment by zxzxwu** [comment]
> Could we instead set a default deadline on GRPC calls ?

It's also a solution, but I didn't find any global timeout/deadline configuration. Or we may manually add timeout to each call, and setup some lint there.

**Comment by zxzxwu** [comment]
> And on server side ?

The safest way is to do on the both side and select the shorter one, but if we must pick one, client side is safer because
* Server implementation might be old
* There might be many kinds of backends(in Avatar's vision) so some of them may not handle well

**Comment by zxzxwu** [comment]
Rebase on https://github.com/google/avatar/pull/58

**Comment by uael** [comment]
WDYT on using literals directly without any forwarded constant ?

**Comment by zxzxwu** [comment]
> WDYT on using literals directly without any forwarded constant ?

That's a good idea. I moved them into an user param.

**Pull request merged**
